dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: opHOmDgY/miF/0EuMG3/EErPkxecSf14gVL/I2PaC2/KcK/WLAQ2cRVA+txwy214Zq07vDe0HXjWIj/3Fm1VRba8OotTSWqdhK/yy/8079Kn9kUVZssw75Ec3Nh9Xpqz7B4y+vItCe3FIWWKmjCye74pt7C8XpOFQNHG7RPkNImRHGIgsWCirDPHebsFx89K0wxZ/mE7X8Jcu23BGOrY8eFwx/VLJL4nJK3sb6zxrYtMe5Vtfdl7i2sLXzR2tDo9sdYJUZ2pUGKx1LyHdWQpfkteIzPp9jBP4Ycxhim887i6RpZBWdPKEugVl3JK9J0jeauvyy5BWPKKQ9PrBUEq1jrR0oIvfnBwH7uN6So/3JMRiWR2YINyWSNQn6DEyHCRphZpRo719j0RDK/76d/GbYQiHJ6Rub0RzKPqXJIs3QAzQwlGcGE6bKIYQ2XhzxQb69X1MKME3k+FFYMW5lcNde41nt2K4qn97cKS2av687933N/QCflRF2y1pOk4Sqt4OS9QuaTHMlGuDFtyFRkcpVHH68ahtvvwV1zcxcbZalMJAUHzVt8O8oMnfgJcyrgselANpxoqjkFlLL58xp2CzqNl3TmxIVC2ZgWpAenBSbyLhnvMXoJnIDxPWKdpXvSTrStDmczGzKy4hTrztWuBNTgqCIMDQOAKE6/837eAkHU=
