---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Configure hosts & deploy application
  hosts: all
  vars:
   db_host: 10.132.0.2
  tasks:
    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/otus.service
      tags: app-tag
      notify: reload otus

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/tihomirovnv/app/db_config
      tags: app-tag

    - name: enable otus
      become: true
      systemd: name=otus enabled=yes
      tags: app-tag

  handlers:
  - name: reload otus
    become: true
    systemd: name=otus state=restarted
...
